platform :ios, '6.0'
pod 'AFNetworking', '~> 2.2.4'
pod 'Reachability', '~> 3.1.1'
pod 'ASIHTTPRequest', '~>1.8.2'
pod 'SDWebImage', '~> 3.7.1'
pod 'RegexKitLite', '~> 4.0'
pod 'OHAttributedLabel', '~> 3.5.4'
pod 'MBProgressHUD', '~> 0.9'
pod 'FMDB', '~> 2.5'
pod 'Masonry'
pod 'MJRefresh'
pod 'ZBarSDK'
pod 'MKNetworkKit'
pod 'LCVoiceHud'
pod 'libqrencode'
pod 'JSONModel'